# example of plan_videos.yml
# mini:
#   - type: youtube
#     url: "https://www.youtube.com/embed/your_youtube_id"
#   - type: google
#     url: "https://drive.google.com/file/d/your_google_id/preview"
# family:
#   - type: youtube
#     url: "https://www.youtube.com/embed/another_youtube_id"
# maximalist: [] # for empty


mini: [
  { type: youtube, url: "https://www.youtube.com/embed/SWmwgy_hnm0" }
]
family: [
  { type: youtube, url: "https://www.youtube.com/embed/SWmwgy_hnm0" }
]
maximalist: [
  { type: youtube, url: "https://www.youtube.com/embed/SWmwgy_hnm0" }
]