# example of plan_videos.yml
# mini:
#   red:
#     - type: youtube
#       url: "https://www.youtube.com/embed/your_youtube_id"
#     - type: google
#       url: "https://drive.google.com/file/d/your_google_id/preview"
# family:
#   orange:
#     - type: youtube
#       url: "https://www.youtube.com/embed/another_youtube_id"
# maximalist: [] # for empty


mini:
  red:
    - { type: youtube, url: "https://www.youtube.com/embed/SWmwgy_hnm0" }
family:
  red:
    - { type: youtube, url: "https://www.youtube.com/embed/SWmwgy_hnm0" }
maximalist:
  red:
    - { type: youtube, url: "https://www.youtube.com/embed/SWmwgy_hnm0" }