name: E2E

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install --no-install-recommends -y curl libjemalloc2 libvips sqlite3

    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install npm dependencies
      run: |
        npm install

    - name: Install Playwright Browsers
      run: |
        npx playwright install --with-deps

    - name: Install dependencies
      run: |
        bundle install

    - name: Install Stripe CLI
      run: |
        curl -s https://packages.stripe.com/api/security/keypair/stripe-cli-gpg | sudo gpg --dearmor -o /usr/share/keyrings/stripe-cli-archive-keyring.gpg && \
        echo "deb [signed-by=/usr/share/keyrings/stripe-cli-archive-keyring.gpg] https://packages.stripe.com/stripe-cli/debian/ stable main" | sudo tee /etc/apt/sources.list.d/stripe-cli.list && \
        sudo apt-get update && \
        sudo apt-get install -y stripe

    - name: Precompile assets
      run: |
        bundle exec rails assets:precompile

    - name: Setup test database
      run: |
        bundle exec rails db:test:prepare

    - name: Run Playwright tests
      run: npx playwright test


    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
