name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        bundle install

    - name: Setup test database
      env:
        RAILS_ENV: test
      run: |
        bundle exec rails db:test:prepare

    - name: Start Rails server
      run: |
        bundle exec rails assets:precompile
        bundle exec foreman start -f Procfile.test &
        sleep 10 # Give the server some time to start

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Stop Rails server
      if: always()
      run: |
        kill $(cat tmp/pids/server.test.pid)

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
